name: Cache APT Packages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cache-apt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Ensure APT cache directory exists
      run: sudo mkdir -p /var/cache/apt

    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('apt-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Update APT and install dependencies
      run: |
        sudo apt-get update
        xargs sudo apt-get install -y < apt-requirements.txt

    - name: Change ownership of APT cache
      run: sudo chown -R $USER:$USER /var/cache/apt
