name: Build and Cache Dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: depends/x86_64-unknown-linux-gnu
          key: ${{ runner.os }}-x86_64-unknown-linux-gnu-${{ hashFiles('depends/**') }}
          restore-keys: |
            ${{ runner.os }}-x86_64-unknown-linux-gnu-

      - name: Run Make
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd depends
          make

      - name: Cache the output directory
        uses: actions/cache@v3
        with:
          path: depends/x86_64-unknown-linux-gnu
          key: ${{ runner.os }}-x86_64-unknown-linux-gnu-${{ hashFiles('depends/**') }}